name: topics_SBE_simonjheiler

channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- pip
- respy==2.0.0dev2
- pre-commit==1.18.3
- interpolation
- pip:
  - grmpy==0.1.1.dev0
